// DMC-Farbtabelle (Garnfarben der Firma DMC)
//
// Diese Datei ist die alleinige Quelle fuer die Funktion "Auf DMC-Farbtabelle
// einrasten" beim Bild-Import im Strickmuster-Editor. Sie liegt bewusst als
// eigene .js-Datei vor (wie lang.js) und nicht in einer austauschbaren .json,
// damit sie nicht versehentlich mit den Muster-Vorlagen geloescht wird.
//
// Einzelne Farben (de-)aktivieren:
//   Feld "active" auf true oder false setzen. Nur Farben mit active: true
//   werden beim Einrasten beruecksichtigt - z.B. wenn ein bestimmtes Garn
//   gerade nicht vorraetig ist. Einfach diese Datei in einem Texteditor
//   oeffnen, die passende Zeile suchen (DMC-Nummer als "code") und den Wert
//   umstellen. Datei danach speichern, Seite im Browser neu laden.
//
// code = DMC-Farbnummer, name = DMC-Farbname (Englisch), hex = Farbwert

const DMC_COLORS = [
  { code: '3713', name: 'Salmon Very Light', hex: '#ffe2e2', active: true },
  { code: '761', name: 'Salmon Light', hex: '#ffc9c9', active: true },
  { code: '760', name: 'Salmon', hex: '#f5adad', active: true },
  { code: '3712', name: 'Salmon Medium', hex: '#f18787', active: true },
  { code: '3328', name: 'Salmon Dark', hex: '#e36d6d', active: true },
  { code: '347', name: 'Salmon Very Dark', hex: '#bf2d2d', active: true },
  { code: '353', name: 'Peach', hex: '#fed7cc', active: true },
  { code: '352', name: 'Coral Light', hex: '#fd9c97', active: true },
  { code: '351', name: 'Coral', hex: '#e96a67', active: true },
  { code: '350', name: 'Coral Medium', hex: '#e04848', active: true },
  { code: '349', name: 'Coral Dark', hex: '#d21035', active: true },
  { code: '817', name: 'Coral Red Very Dark', hex: '#bb051f', active: true },
  { code: '3708', name: 'Melon Light', hex: '#ffcbd5', active: true },
  { code: '3706', name: 'Melon Medium', hex: '#ffadbc', active: true },
  { code: '3705', name: 'Melon Dark', hex: '#ff7992', active: true },
  { code: '3801', name: 'Melon Very Dark', hex: '#e74967', active: true },
  { code: '666', name: 'Bright Red', hex: '#e31d42', active: true },
  { code: '321', name: 'Red', hex: '#c72b3b', active: true },
  { code: '304', name: 'Red Medium', hex: '#b71f33', active: true },
  { code: '498', name: 'Red Dark', hex: '#a7132b', active: true },
  { code: '816', name: 'Garnet', hex: '#970b23', active: true },
  { code: '815', name: 'Garnet Medium', hex: '#87071f', active: true },
  { code: '814', name: 'Garnet Dark', hex: '#7b001b', active: true },
  { code: '894', name: 'Carnation Very Light', hex: '#ffb2bb', active: true },
  { code: '893', name: 'Carnation Light', hex: '#fc90a2', active: true },
  { code: '892', name: 'Carnation Medium', hex: '#ff798c', active: true },
  { code: '891', name: 'Carnation Dark', hex: '#ff5773', active: true },
  { code: '818', name: 'Baby Pink', hex: '#ffdfd9', active: true },
  { code: '957', name: 'Geranium Pale', hex: '#fdb5b5', active: true },
  { code: '956', name: 'Geranium', hex: '#ff9191', active: true },
  { code: '309', name: 'Rose Dark', hex: '#d62b5b', active: true },
  { code: '963', name: 'Dusty Rose Ult Vy Lt', hex: '#ffd7d7', active: true },
  { code: '3716', name: 'Dusty Rose Med Vy Lt', hex: '#ffbdbd', active: true },
  { code: '962', name: 'Dusty Rose Medium', hex: '#e68a8a', active: true },
  { code: '961', name: 'Dusty Rose Dark', hex: '#cf7373', active: true },
  { code: '3833', name: 'Raspberry Light', hex: '#ea8699', active: true },
  { code: '3832', name: 'Raspberry Medium', hex: '#db556e', active: true },
  { code: '3831', name: 'Raspberry Dark', hex: '#b32f48', active: true },
  { code: '777', name: 'Raspberry Very Dark', hex: '#913546', active: true },
  { code: '819', name: 'Baby Pink Light', hex: '#ffeeeb', active: true },
  { code: '3326', name: 'Rose Light', hex: '#fbadb4', active: true },
  { code: '776', name: 'Pink Medium', hex: '#fcb0b9', active: true },
  { code: '899', name: 'Rose Medium', hex: '#f27688', active: true },
  { code: '335', name: 'Rose', hex: '#ee546e', active: true },
  { code: '326', name: 'Rose Very Dark', hex: '#b33b4b', active: true },
  { code: '151', name: 'Dusty Rose Vry Lt', hex: '#f0ced4', active: true },
  { code: '3354', name: 'Dusty Rose Light', hex: '#e4a6ac', active: true },
  { code: '3733', name: 'Dusty Rose', hex: '#e8879b', active: true },
  { code: '3731', name: 'Dusty Rose Very Dark', hex: '#da6783', active: true },
  { code: '3350', name: 'Dusty Rose Ultra Dark', hex: '#bc4365', active: true },
  { code: '150', name: 'Dusty Rose Ult Vy Dk', hex: '#ab0249', active: true },
  { code: '3689', name: 'Mauve Light', hex: '#fbbfc2', active: true },
  { code: '3688', name: 'Mauve Medium', hex: '#e7a9ac', active: true },
  { code: '3687', name: 'Mauve', hex: '#c96b70', active: true },
  { code: '3803', name: 'Mauve Dark', hex: '#ab3357', active: true },
  { code: '3685', name: 'Mauve Very Dark', hex: '#881531', active: true },
  { code: '605', name: 'Cranberry Very Light', hex: '#ffc0cd', active: true },
  { code: '604', name: 'Cranberry Light', hex: '#ffb0be', active: true },
  { code: '603', name: 'Cranberry', hex: '#ffa4be', active: true },
  { code: '602', name: 'Cranberry Medium', hex: '#e24874', active: true },
  { code: '601', name: 'Cranberry Dark', hex: '#d1286a', active: true },
  { code: '600', name: 'Cranberry Very Dark', hex: '#cd2f63', active: true },
  { code: '3806', name: 'Cyclamen Pink Light', hex: '#ff8cae', active: true },
  { code: '3805', name: 'Cyclamen Pink', hex: '#f3478b', active: true },
  { code: '3804', name: 'Cyclamen Pink Dark', hex: '#e02876', active: true },
  { code: '3609', name: 'Plum Ultra Light', hex: '#f4aed5', active: true },
  { code: '3608', name: 'Plum Very Light', hex: '#ea9cc4', active: true },
  { code: '3607', name: 'Plum Light', hex: '#c54989', active: true },
  { code: '718', name: 'Plum', hex: '#9c2462', active: true },
  { code: '917', name: 'Plum Medium', hex: '#9b1359', active: true },
  { code: '915', name: 'Plum Dark', hex: '#820043', active: true },
  { code: '225', name: 'Shell Pink Ult Vy Lt', hex: '#ffdfd5', active: true },
  { code: '224', name: 'Shell Pink Very Light', hex: '#ebb7af', active: true },
  { code: '152', name: 'Shell Pink Med Light', hex: '#e2a099', active: true },
  { code: '223', name: 'Shell Pink Light', hex: '#cc847c', active: true },
  { code: '3722', name: 'Shell Pink Med', hex: '#bc6c64', active: true },
  { code: '3721', name: 'Shell Pink Dark', hex: '#a14b51', active: true },
  { code: '221', name: 'Shell Pink Vy Dk', hex: '#883e43', active: true },
  { code: '778', name: 'Antique Mauve Vy Lt', hex: '#dfb3bb', active: true },
  { code: '3727', name: 'Antique Mauve Light', hex: '#dba9b2', active: true },
  { code: '316', name: 'Antique Mauve Med', hex: '#b7737f', active: true },
  { code: '3726', name: 'Antique Mauve Dark', hex: '#9b5b66', active: true },
  { code: '315', name: 'Antique Mauve Md Dk', hex: '#814952', active: true },
  { code: '3802', name: 'Antique Mauve Vy Dk', hex: '#714149', active: true },
  { code: '902', name: 'Garnet Very Dark', hex: '#822637', active: true },
  { code: '3743', name: 'Antique Violet Vy Lt', hex: '#d7cbd3', active: true },
  { code: '3042', name: 'Antique Violet Light', hex: '#b79da7', active: true },
  { code: '3041', name: 'Antique Violet Medium', hex: '#956f7c', active: true },
  { code: '3740', name: 'Antique Violet Dark', hex: '#785762', active: true },
  { code: '3836', name: 'Grape Light', hex: '#ba91aa', active: true },
  { code: '3835', name: 'Grape Medium', hex: '#946083', active: true },
  { code: '3834', name: 'Grape Dark', hex: '#72375d', active: true },
  { code: '154', name: 'Grape Very Dark', hex: '#572433', active: true },
  { code: '211', name: 'Lavender Light', hex: '#e3cbe3', active: true },
  { code: '210', name: 'Lavender Medium', hex: '#c39fc3', active: true },
  { code: '209', name: 'Lavender Dark', hex: '#a37ba7', active: true },
  { code: '208', name: 'Lavender Very Dark', hex: '#835b8b', active: true },
  { code: '3837', name: 'Lavender Ultra Dark', hex: '#6c3a6e', active: true },
  { code: '327', name: 'Violet Dark', hex: '#633666', active: true },
  { code: '153', name: 'Violet Very Light', hex: '#e6ccd9', active: true },
  { code: '554', name: 'Violet Light', hex: '#dbb3cb', active: true },
  { code: '553', name: 'Violet', hex: '#a3638b', active: true },
  { code: '552', name: 'Violet Medium', hex: '#803a6b', active: true },
  { code: '550', name: 'Violet Very Dark', hex: '#5c184e', active: true },
  { code: '3747', name: 'Blue Violet Vy Lt', hex: '#d3d7ed', active: true },
  { code: '341', name: 'Blue Violet Light', hex: '#b7bfdd', active: true },
  { code: '156', name: 'Blue Violet Med Lt', hex: '#a3aed1', active: true },
  { code: '340', name: 'Blue Violet Medium', hex: '#ada7c7', active: true },
  { code: '155', name: 'Blue Violet Med Dark', hex: '#9891b6', active: true },
  { code: '3746', name: 'Blue Violet Dark', hex: '#776b98', active: true },
  { code: '333', name: 'Blue Violet Very Dark', hex: '#5c5478', active: true },
  { code: '157', name: 'Cornflower Blue Vy Lt', hex: '#bbc3d9', active: true },
  { code: '794', name: 'Cornflower Blue Light', hex: '#8f9cc1', active: true },
  { code: '793', name: 'Cornflower Blue Med', hex: '#707da2', active: true },
  { code: '3807', name: 'Cornflower Blue', hex: '#60678c', active: true },
  { code: '792', name: 'Cornflower Blue Dark', hex: '#555b7b', active: true },
  { code: '158', name: 'Cornflower Blu M V D', hex: '#4c526e', active: true },
  { code: '791', name: 'Cornflower Blue V D', hex: '#464563', active: true },
  { code: '3840', name: 'Lavender Blue Light', hex: '#b0c0da', active: true },
  { code: '3839', name: 'Lavender Blue Med', hex: '#7b8eab', active: true },
  { code: '3838', name: 'Lavender Blue Dark', hex: '#5c7294', active: true },
  { code: '800', name: 'Delft Blue Pale', hex: '#c0ccde', active: true },
  { code: '809', name: 'Delft Blue', hex: '#94a8c6', active: true },
  { code: '799', name: 'Delft Blue Medium', hex: '#748eb6', active: true },
  { code: '798', name: 'Delft Blue Dark', hex: '#466a8e', active: true },
  { code: '797', name: 'Royal Blue', hex: '#13477d', active: true },
  { code: '796', name: 'Royal Blue Dark', hex: '#11416d', active: true },
  { code: '820', name: 'Royal Blue Very Dark', hex: '#0e365c', active: true },
  { code: '162', name: 'Blue Ultra Very Light', hex: '#dbecf5', active: true },
  { code: '827', name: 'Blue Very Light', hex: '#bddded', active: true },
  { code: '813', name: 'Blue Light', hex: '#a1c2d7', active: true },
  { code: '826', name: 'Blue Medium', hex: '#6b9ebf', active: true },
  { code: '825', name: 'Blue Dark', hex: '#4781a5', active: true },
  { code: '824', name: 'Blue Very Dark', hex: '#396987', active: true },
  { code: '996', name: 'Electric Blue Medium', hex: '#30c2ec', active: true },
  { code: '3843', name: 'Electric Blue', hex: '#14aad0', active: true },
  { code: '995', name: 'Electric Blue Dark', hex: '#2696b6', active: true },
  { code: '3846', name: 'Turquoise Bright Light', hex: '#06e3e6', active: true },
  { code: '3845', name: 'Turquoise Bright Med', hex: '#04c4ca', active: true },
  { code: '3844', name: 'Turquoise Bright Dark', hex: '#12aeba', active: true },
  { code: '159', name: 'Blue Gray Light', hex: '#c7cad7', active: true },
  { code: '160', name: 'Blue Gray Medium', hex: '#999fb7', active: true },
  { code: '161', name: 'Blue Gray', hex: '#7880a4', active: true },
  { code: '3756', name: 'Baby Blue Ult Vy Lt', hex: '#eefcfc', active: true },
  { code: '775', name: 'Baby Blue Very Light', hex: '#d9ebf1', active: true },
  { code: '3841', name: 'Baby Blue Pale', hex: '#cddfed', active: true },
  { code: '3325', name: 'Baby Blue Light', hex: '#b8d2e6', active: true },
  { code: '3755', name: 'Baby Blue', hex: '#93b4ce', active: true },
  { code: '334', name: 'Baby Blue Medium', hex: '#739fc1', active: true },
  { code: '322', name: 'Baby Blue Dark', hex: '#5a8fb8', active: true },
  { code: '312', name: 'Baby Blue Very Dark', hex: '#35668b', active: true },
  { code: '803', name: 'Baby Blue Ult Vy Dk', hex: '#2c597c', active: true },
  { code: '336', name: 'Navy Blue', hex: '#253b73', active: true },
  { code: '823', name: 'Navy Blue Dark', hex: '#213063', active: true },
  { code: '939', name: 'Navy Blue Very Dark', hex: '#1b2853', active: true },
  { code: '3753', name: 'Antique Blue Ult Vy Lt', hex: '#dbe2e9', active: true },
  { code: '3752', name: 'Antique Blue Very Lt', hex: '#c7d1db', active: true },
  { code: '932', name: 'Antique Blue Light', hex: '#a2b5c6', active: true },
  { code: '931', name: 'Antique Blue Medium', hex: '#6a859e', active: true },
  { code: '930', name: 'Antique Blue Dark', hex: '#455c71', active: true },
  { code: '3750', name: 'Antique Blue Very Dk', hex: '#384c5e', active: true },
  { code: '828', name: 'Sky Blue Vy Lt', hex: '#c5e8ed', active: true },
  { code: '3761', name: 'Sky Blue Light', hex: '#acd8e2', active: true },
  { code: '519', name: 'Sky Blue', hex: '#7eb1c8', active: true },
  { code: '518', name: 'Wedgewood Light', hex: '#4f93a7', active: true },
  { code: '3760', name: 'Wedgewood Med', hex: '#3e85a2', active: true },
  { code: '517', name: 'Wedgewood Dark', hex: '#3b768f', active: true },
  { code: '3842', name: 'Wedgewood Vry Dk', hex: '#32667c', active: true },
  { code: '311', name: 'Wedgewood Ult VyDk', hex: '#1c5066', active: true },
  { code: '747', name: 'Peacock Blue Vy Lt', hex: '#e5fcfd', active: true },
  { code: '3766', name: 'Peacock Blue Light', hex: '#99cfd9', active: true },
  { code: '807', name: 'Peacock Blue', hex: '#64abba', active: true },
  { code: '806', name: 'Peacock Blue Dark', hex: '#3d95a5', active: true },
  { code: '3765', name: 'Peacock Blue Vy Dk', hex: '#347f8c', active: true },
  { code: '3811', name: 'Turquoise Very Light', hex: '#bce3e6', active: true },
  { code: '598', name: 'Turquoise Light', hex: '#90c3cc', active: true },
  { code: '597', name: 'Turquoise', hex: '#5ba3b3', active: true },
  { code: '3810', name: 'Turquoise Dark', hex: '#488e9a', active: true },
  { code: '3809', name: 'Turquoise Vy Dark', hex: '#3f7c85', active: true },
  { code: '3808', name: 'Turquoise Ult Vy Dk', hex: '#366970', active: true },
  { code: '928', name: 'Gray Green Vy Lt', hex: '#dde3e3', active: true },
  { code: '927', name: 'Gray Green Light', hex: '#bdcbcb', active: true },
  { code: '926', name: 'Gray Green Med', hex: '#98aeae', active: true },
  { code: '3768', name: 'Gray Green Dark', hex: '#657f7f', active: true },
  { code: '924', name: 'Gray Green Vy Dark', hex: '#566a6a', active: true },
  { code: '3849', name: 'Teal Green Light', hex: '#52b3a4', active: true },
  { code: '3848', name: 'Teal Green Med', hex: '#559392', active: true },
  { code: '3847', name: 'Teal Green Dark', hex: '#347d75', active: true },
  { code: '964', name: 'Sea Green Light', hex: '#a9e2d8', active: true },
  { code: '959', name: 'Sea Green Med', hex: '#59c7b4', active: true },
  { code: '958', name: 'Sea Green Dark', hex: '#3eb6a1', active: true },
  { code: '3812', name: 'Sea Green Vy Dk', hex: '#2f8c84', active: true },
  { code: '3851', name: 'Green Bright Lt', hex: '#49b3a1', active: true },
  { code: '943', name: 'Green Bright Md', hex: '#3d9384', active: true },
  { code: '3850', name: 'Green Bright Dk', hex: '#378477', active: true },
  { code: '993', name: 'Aquamarine Vy Lt', hex: '#90c0b4', active: true },
  { code: '992', name: 'Aquamarine Lt', hex: '#6fae9f', active: true },
  { code: '3814', name: 'Aquamarine', hex: '#508b7d', active: true },
  { code: '991', name: 'Aquamarine Dk', hex: '#477b6e', active: true },
  { code: '966', name: 'Jade Ultra Vy Lt', hex: '#b9d7c0', active: true },
  { code: '564', name: 'Jade Very Light', hex: '#a7cdaf', active: true },
  { code: '563', name: 'Jade Light', hex: '#8fc098', active: true },
  { code: '562', name: 'Jade Medium', hex: '#53976a', active: true },
  { code: '505', name: 'Jade Green', hex: '#338362', active: true },
  { code: '3817', name: 'Celadon Green Lt', hex: '#99c3aa', active: true },
  { code: '3816', name: 'Celadon Green', hex: '#65a57d', active: true },
  { code: '163', name: 'Celadon Green Md', hex: '#4d8361', active: true },
  { code: '3815', name: 'Celadon Green Dk', hex: '#477759', active: true },
  { code: '561', name: 'Celadon Green VD', hex: '#2c6a45', active: true },
  { code: '504', name: 'Blue Green Vy Lt', hex: '#c4decc', active: true },
  { code: '3813', name: 'Blue Green Lt', hex: '#b2d4bd', active: true },
  { code: '503', name: 'Blue Green Med', hex: '#7bac94', active: true },
  { code: '502', name: 'Blue Green', hex: '#5b9071', active: true },
  { code: '501', name: 'Blue Green Dark', hex: '#396f52', active: true },
  { code: '500', name: 'Blue Green Vy Dk', hex: '#044d33', active: true },
  { code: '955', name: 'Nile Green Light', hex: '#a2d6ad', active: true },
  { code: '954', name: 'Nile Green', hex: '#88ba91', active: true },
  { code: '913', name: 'Nile Green Med', hex: '#6dab77', active: true },
  { code: '912', name: 'Emerald Green Lt', hex: '#1b9d6b', active: true },
  { code: '911', name: 'Emerald Green Med', hex: '#189065', active: true },
  { code: '910', name: 'Emerald Green Dark', hex: '#187e56', active: true },
  { code: '909', name: 'Emerald Green Vy Dk', hex: '#156f49', active: true },
  { code: '3818', name: 'Emerald Grn Ult V Dk', hex: '#115a3b', active: true },
  { code: '369', name: 'Pistachio Green Vy Lt', hex: '#d7edcc', active: true },
  { code: '368', name: 'Pistachio Green Lt', hex: '#a6c298', active: true },
  { code: '320', name: 'Pistachio Green Med', hex: '#69885a', active: true },
  { code: '367', name: 'Pistachio Green Dk', hex: '#617a52', active: true },
  { code: '319', name: 'Pistachio Grn Vy Dk', hex: '#205f2e', active: true },
  { code: '890', name: 'Pistachio Grn Ult V D', hex: '#174923', active: true },
  { code: '164', name: 'Forest Green Lt', hex: '#c8d8b8', active: true },
  { code: '989', name: 'Forest Green', hex: '#8da675', active: true },
  { code: '988', name: 'Forest Green Med', hex: '#738b5b', active: true },
  { code: '987', name: 'Forest Green Dk', hex: '#587141', active: true },
  { code: '986', name: 'Forest Green Vy Dk', hex: '#405230', active: true },
  { code: '772', name: 'Yellow Green Vy Lt', hex: '#e4ecd4', active: true },
  { code: '3348', name: 'Yellow Green Lt', hex: '#ccd9b1', active: true },
  { code: '3347', name: 'Yellow Green Med', hex: '#71935c', active: true },
  { code: '3346', name: 'Hunter Green', hex: '#406a3a', active: true },
  { code: '3345', name: 'Hunter Green Dk', hex: '#1b5915', active: true },
  { code: '895', name: 'Hunter Green Vy Dk', hex: '#1b5300', active: true },
  { code: '704', name: 'Chartreuse Bright', hex: '#9ecf34', active: true },
  { code: '703', name: 'Chartreuse', hex: '#7bb547', active: true },
  { code: '702', name: 'Kelly Green', hex: '#47a72f', active: true },
  { code: '701', name: 'Green Light', hex: '#3f8f29', active: true },
  { code: '700', name: 'Green Bright', hex: '#07731b', active: true },
  { code: '699', name: 'Green', hex: '#056517', active: true },
  { code: '907', name: 'Parrot Green Lt', hex: '#c7e666', active: true },
  { code: '906', name: 'Parrot Green Md', hex: '#7fb335', active: true },
  { code: '905', name: 'Parrot Green Dk', hex: '#628a28', active: true },
  { code: '904', name: 'Parrot Green V Dk', hex: '#557822', active: true },
  { code: '472', name: 'Avocado Grn U Lt', hex: '#d8e498', active: true },
  { code: '471', name: 'Avocado Grn V Lt', hex: '#aebf79', active: true },
  { code: '470', name: 'Avocado Grn Lt', hex: '#94ab4f', active: true },
  { code: '469', name: 'Avocado Green', hex: '#72843c', active: true },
  { code: '937', name: 'Avocado Green Md', hex: '#627133', active: true },
  { code: '936', name: 'Avocado Grn V Dk', hex: '#4c5826', active: true },
  { code: '935', name: 'Avocado Green Dk', hex: '#424d21', active: true },
  { code: '934', name: 'Avocado Grn Black', hex: '#313919', active: true },
  { code: '523', name: 'Fern Green Lt', hex: '#abb197', active: true },
  { code: '3053', name: 'Green Gray', hex: '#9ca482', active: true },
  { code: '3052', name: 'Green Gray Md', hex: '#889268', active: true },
  { code: '3051', name: 'Green Gray Dk', hex: '#5f6648', active: true },
  { code: '524', name: 'Fern Green Vy Lt', hex: '#c4cdac', active: true },
  { code: '522', name: 'Fern Green', hex: '#969e7e', active: true },
  { code: '520', name: 'Fern Green Dark', hex: '#666d4f', active: true },
  { code: '3364', name: 'Pine Green', hex: '#83975f', active: true },
  { code: '3363', name: 'Pine Green Md', hex: '#728256', active: true },
  { code: '3362', name: 'Pine Green Dk', hex: '#5e6b47', active: true },
  { code: '165', name: 'Moss Green Vy Lt', hex: '#eff4a4', active: true },
  { code: '3819', name: 'Moss Green Lt', hex: '#e0e868', active: true },
  { code: '166', name: 'Moss Green Md Lt', hex: '#c0c840', active: true },
  { code: '581', name: 'Moss Green', hex: '#a7ae38', active: true },
  { code: '580', name: 'Moss Green Dk', hex: '#888d33', active: true },
  { code: '734', name: 'Olive Green Lt', hex: '#c7c077', active: true },
  { code: '733', name: 'Olive Green Md', hex: '#bcb34c', active: true },
  { code: '732', name: 'Olive Green', hex: '#948c36', active: true },
  { code: '731', name: 'Olive Green Dk', hex: '#938b37', active: true },
  { code: '730', name: 'Olive Green V Dk', hex: '#827b30', active: true },
  { code: '3013', name: 'Khaki Green Lt', hex: '#b9b982', active: true },
  { code: '3012', name: 'Khaki Green Md', hex: '#a6a75d', active: true },
  { code: '3011', name: 'Khaki Green Dk', hex: '#898a58', active: true },
  { code: '372', name: 'Mustard Lt', hex: '#ccb784', active: true },
  { code: '371', name: 'Mustard', hex: '#bfa671', active: true },
  { code: '370', name: 'Mustard Medium', hex: '#b89d64', active: true },
  { code: '834', name: 'Golden Olive Vy Lt', hex: '#dbbe7f', active: true },
  { code: '833', name: 'Golden Olive Lt', hex: '#c8ab6c', active: true },
  { code: '832', name: 'Golden Olive', hex: '#bd9b51', active: true },
  { code: '831', name: 'Golden Olive Md', hex: '#aa8f56', active: true },
  { code: '830', name: 'Golden Olive Dk', hex: '#8d784b', active: true },
  { code: '829', name: 'Golden Olive Vy Dk', hex: '#7e6b42', active: true },
  { code: '613', name: 'Drab Brown V Lt', hex: '#dcc4aa', active: true },
  { code: '612', name: 'Drab Brown Lt', hex: '#bc9a78', active: true },
  { code: '611', name: 'Drab Brown', hex: '#967656', active: true },
  { code: '610', name: 'Drab Brown Dk', hex: '#796047', active: true },
  { code: '3047', name: 'Yellow Beige Lt', hex: '#e7d6c1', active: true },
  { code: '3046', name: 'Yellow Beige Md', hex: '#d8bc9a', active: true },
  { code: '3045', name: 'Yellow Beige Dk', hex: '#bc966a', active: true },
  { code: '167', name: 'Yellow Beige V Dk', hex: '#a77c49', active: true },
  { code: '746', name: 'Off White', hex: '#fcfcee', active: true },
  { code: '677', name: 'Old Gold Vy Lt', hex: '#f5eccb', active: true },
  { code: '422', name: 'Hazelnut Brown Lt', hex: '#c69f7b', active: true },
  { code: '3828', name: 'Hazelnut Brown', hex: '#b78b61', active: true },
  { code: '420', name: 'Hazelnut Brown Dk', hex: '#a07042', active: true },
  { code: '869', name: 'Hazelnut Brown V Dk', hex: '#835e39', active: true },
  { code: '728', name: 'Topaz', hex: '#e4b468', active: true },
  { code: '783', name: 'Topaz Medium', hex: '#ce9124', active: true },
  { code: '782', name: 'Topaz Dark', hex: '#ae7720', active: true },
  { code: '781', name: 'Topaz Very Dark', hex: '#a26d20', active: true },
  { code: '780', name: 'Topaz Ultra Vy Dk', hex: '#94631a', active: true },
  { code: '676', name: 'Old Gold Lt', hex: '#e5ce97', active: true },
  { code: '729', name: 'Old Gold Medium', hex: '#d0a53e', active: true },
  { code: '680', name: 'Old Gold Dark', hex: '#bc8d0e', active: true },
  { code: '3829', name: 'Old Gold Vy Dark', hex: '#a98204', active: true },
  { code: '3822', name: 'Straw Light', hex: '#f6dc98', active: true },
  { code: '3821', name: 'Straw', hex: '#f3ce75', active: true },
  { code: '3820', name: 'Straw Dark', hex: '#dfb65f', active: true },
  { code: '3852', name: 'Straw Very Dark', hex: '#cd9d37', active: true },
  { code: '445', name: 'Lemon Light', hex: '#fffb8b', active: true },
  { code: '307', name: 'Lemon', hex: '#fded54', active: true },
  { code: '973', name: 'Canary Bright', hex: '#ffe300', active: true },
  { code: '444', name: 'Lemon Dark', hex: '#ffd600', active: true },
  { code: '3078', name: 'Golden Yellow Vy Lt', hex: '#fdf9cd', active: true },
  { code: '727', name: 'Topaz Vy Lt', hex: '#fff1af', active: true },
  { code: '726', name: 'Topaz Light', hex: '#fdd755', active: true },
  { code: '725', name: 'Topaz Med Lt', hex: '#ffc840', active: true },
  { code: '972', name: 'Canary Deep', hex: '#ffb515', active: true },
  { code: '745', name: 'Yellow Pale Light', hex: '#ffe9ad', active: true },
  { code: '744', name: 'Yellow Pale', hex: '#ffe793', active: true },
  { code: '743', name: 'Yellow Med', hex: '#fed376', active: true },
  { code: '742', name: 'Tangerine Light', hex: '#ffbf57', active: true },
  { code: '741', name: 'Tangerine Med', hex: '#ffa32b', active: true },
  { code: '740', name: 'Tangerine', hex: '#ff8b00', active: true },
  { code: '970', name: 'Pumpkin Light', hex: '#f78b13', active: true },
  { code: '971', name: 'Pumpkin', hex: '#f67f00', active: true },
  { code: '947', name: 'Burnt Orange', hex: '#ff7b4d', active: true },
  { code: '946', name: 'Burnt Orange Med', hex: '#eb6307', active: true },
  { code: '900', name: 'Burnt Orange Dark', hex: '#d15807', active: true },
  { code: '967', name: 'Apricot Very Light', hex: '#ffded5', active: true },
  { code: '3824', name: 'Apricot Light', hex: '#fecdc2', active: true },
  { code: '3341', name: 'Apricot', hex: '#fcab98', active: true },
  { code: '3340', name: 'Apricot Med', hex: '#ff836f', active: true },
  { code: '608', name: 'Burnt Orange Bright', hex: '#fd5d35', active: true },
  { code: '606', name: 'Orange Red Bright', hex: '#fa3203', active: true },
  { code: '951', name: 'Tawny Light', hex: '#ffe2cf', active: true },
  { code: '3856', name: 'Mahogany Ult Vy Lt', hex: '#ffd3b5', active: true },
  { code: '722', name: 'Orange Spice Light', hex: '#f7976f', active: true },
  { code: '721', name: 'Orange Spice Med', hex: '#f27842', active: true },
  { code: '720', name: 'Orange Spice Dark', hex: '#e55c1f', active: true },
  { code: '3825', name: 'Pumpkin Pale', hex: '#fdbd96', active: true },
  { code: '922', name: 'Copper Light', hex: '#e27323', active: true },
  { code: '921', name: 'Copper', hex: '#c66218', active: true },
  { code: '920', name: 'Copper Med', hex: '#ac5414', active: true },
  { code: '919', name: 'Red Copper', hex: '#a64510', active: true },
  { code: '918', name: 'Red Copper Dark', hex: '#82340a', active: true },
  { code: '3770', name: 'Tawny Vy Light', hex: '#ffeee3', active: true },
  { code: '945', name: 'Tawny', hex: '#fbd5bb', active: true },
  { code: '402', name: 'Mahogany Vy Lt', hex: '#f7a777', active: true },
  { code: '3776', name: 'Mahogany Light', hex: '#cf7939', active: true },
  { code: '301', name: 'Mahogany Med', hex: '#b35f2b', active: true },
  { code: '400', name: 'Mahogany Dark', hex: '#8f430f', active: true },
  { code: '300', name: 'Mahogany Vy Dk', hex: '#6f2f00', active: true },
  { code: '3823', name: 'Yellow Ultra Pale', hex: '#fffde3', active: true },
  { code: '3855', name: 'Autumn Gold Lt', hex: '#fad396', active: true },
  { code: '3854', name: 'Autumn Gold Med', hex: '#f2af68', active: true },
  { code: '3853', name: 'Autumn Gold Dk', hex: '#f29746', active: true },
  { code: '3827', name: 'Golden Brown Pale', hex: '#f7bb77', active: true },
  { code: '977', name: 'Golden Brown Light', hex: '#dc9c56', active: true },
  { code: '976', name: 'Golden Brown Med', hex: '#c28142', active: true },
  { code: '3826', name: 'Golden Brown', hex: '#ad7239', active: true },
  { code: '975', name: 'Golden Brown Dk', hex: '#914f12', active: true },
  { code: '948', name: 'Peach Very Light', hex: '#fee7da', active: true },
  { code: '754', name: 'Peach Light', hex: '#f7cbbf', active: true },
  { code: '3771', name: 'Terra Cotta Ult Vy Lt', hex: '#f4bba9', active: true },
  { code: '758', name: 'Terra Cotta Vy Lt', hex: '#eeaa9b', active: true },
  { code: '3778', name: 'Terra Cotta Light', hex: '#d98978', active: true },
  { code: '356', name: 'Terra Cotta Med', hex: '#c56a5b', active: true },
  { code: '3830', name: 'Terra Cotta', hex: '#b95544', active: true },
  { code: '355', name: 'Terra Cotta Dark', hex: '#984436', active: true },
  { code: '3777', name: 'Terra Cotta Vy Dk', hex: '#863022', active: true },
  { code: '3779', name: 'Rosewood Ult Vy Lt', hex: '#f8cac8', active: true },
  { code: '3859', name: 'Rosewood Light', hex: '#ba8b7c', active: true },
  { code: '3858', name: 'Rosewood Med', hex: '#964a3f', active: true },
  { code: '3857', name: 'Rosewood Dark', hex: '#68251a', active: true },
  { code: '3774', name: 'Desert Sand Vy Lt', hex: '#f3e1d7', active: true },
  { code: '950', name: 'Desert Sand Light', hex: '#eed3c4', active: true },
  { code: '3064', name: 'Desert Sand', hex: '#c48e70', active: true },
  { code: '407', name: 'Desert Sand Med', hex: '#bb8161', active: true },
  { code: '3773', name: 'Desert Sand Dark', hex: '#b67552', active: true },
  { code: '3772', name: 'Desert Sand Vy Dk', hex: '#a06c50', active: true },
  { code: '632', name: 'Desert Sand Ult Vy Dk', hex: '#875539', active: true },
  { code: '453', name: 'Shell Gray Light', hex: '#d7cecb', active: true },
  { code: '452', name: 'Shell Gray Med', hex: '#c0b3ae', active: true },
  { code: '451', name: 'Shell Gray Dark', hex: '#917b73', active: true },
  { code: '3861', name: 'Cocoa Light', hex: '#a68881', active: true },
  { code: '3860', name: 'Cocoa', hex: '#7d5d57', active: true },
  { code: '779', name: 'Cocoa Dark', hex: '#624b45', active: true },
  { code: '712', name: 'Cream', hex: '#fffbef', active: true },
  { code: '739', name: 'Tan Ult Vy Lt', hex: '#f8e4c8', active: true },
  { code: '738', name: 'Tan Very Light', hex: '#eccc9e', active: true },
  { code: '437', name: 'Tan Light', hex: '#e4bb8e', active: true },
  { code: '436', name: 'Tan', hex: '#cb9051', active: true },
  { code: '435', name: 'Brown Very Light', hex: '#b87748', active: true },
  { code: '434', name: 'Brown Light', hex: '#985e33', active: true },
  { code: '433', name: 'Brown Med', hex: '#7a451f', active: true },
  { code: '801', name: 'Coffee Brown Dk', hex: '#653919', active: true },
  { code: '898', name: 'Coffee Brown Vy Dk', hex: '#492a13', active: true },
  { code: '938', name: 'Coffee Brown Ult Dk', hex: '#361f0e', active: true },
  { code: '3371', name: 'Black Brown', hex: '#1e1108', active: true },
  { code: '543', name: 'Beige Brown Ult Vy Lt', hex: '#f2e3ce', active: true },
  { code: '3864', name: 'Mocha Beige Light', hex: '#cbb69c', active: true },
  { code: '3863', name: 'Mocha Beige Med', hex: '#a4835c', active: true },
  { code: '3862', name: 'Mocha Beige Dark', hex: '#8a6e4e', active: true },
  { code: '3031', name: 'Mocha Brown Vy Dk', hex: '#4b3c2a', active: true },
  { code: 'B5200', name: 'Snow White', hex: '#ffffff', active: true },
  { code: 'White', name: 'White', hex: '#fcfbf8', active: true },
  { code: '3865', name: 'Winter White', hex: '#f9f7f1', active: true },
  { code: 'Ecru', name: 'Ecru', hex: '#f0eada', active: true },
  { code: '822', name: 'Beige Gray Light', hex: '#e7e2d3', active: true },
  { code: '644', name: 'Beige Gray Med', hex: '#ddd8cb', active: true },
  { code: '642', name: 'Beige Gray Dark', hex: '#a49878', active: true },
  { code: '640', name: 'Beige Gray Vy Dk', hex: '#857b61', active: true },
  { code: '3787', name: 'Brown Gray Dark', hex: '#625d50', active: true },
  { code: '3021', name: 'Brown Gray Vy Dk', hex: '#4f4b41', active: true },
  { code: '3024', name: 'Brown Gray Vy Lt', hex: '#ebeae7', active: true },
  { code: '3023', name: 'Brown Gray Light', hex: '#b1aa97', active: true },
  { code: '3022', name: 'Brown Gray Med', hex: '#8e9078', active: true },
  { code: '535', name: 'Ash Gray Vy Lt', hex: '#636458', active: true },
  { code: '3033', name: 'Mocha Brown Vy Lt', hex: '#e3d8cc', active: true },
  { code: '3782', name: 'Mocha Brown Lt', hex: '#d2bca6', active: true },
  { code: '3032', name: 'Mocha Brown Med', hex: '#b39f8b', active: true },
  { code: '3790', name: 'Beige Gray Ult Dk', hex: '#7f6a55', active: true },
  { code: '3781', name: 'Mocha Brown Dk', hex: '#6b5743', active: true },
  { code: '3866', name: 'Mocha Brn Ult Vy Lt', hex: '#faf6f0', active: true },
  { code: '842', name: 'Beige Brown Vy Lt', hex: '#d1baa1', active: true },
  { code: '841', name: 'Beige Brown Lt', hex: '#b69b7e', active: true },
  { code: '840', name: 'Beige Brown Med', hex: '#9a7c5c', active: true },
  { code: '839', name: 'Beige Brown Dk', hex: '#675541', active: true },
  { code: '838', name: 'Beige Brown Vy Dk', hex: '#594937', active: true },
  { code: '3072', name: 'Beaver Gray Vy Lt', hex: '#e6e8e8', active: true },
  { code: '648', name: 'Beaver Gray Lt', hex: '#bcb4ac', active: true },
  { code: '647', name: 'Beaver Gray Med', hex: '#b0a69c', active: true },
  { code: '646', name: 'Beaver Gray Dk', hex: '#877d73', active: true },
  { code: '645', name: 'Beaver Gray Vy Dk', hex: '#6e655c', active: true },
  { code: '844', name: 'Beaver Gray Ult Dk', hex: '#484848', active: true },
  { code: '762', name: 'Pearl Gray Vy Lt', hex: '#ececec', active: true },
  { code: '415', name: 'Pearl Gray', hex: '#d3d3d6', active: true },
  { code: '318', name: 'Steel Gray Lt', hex: '#ababab', active: true },
  { code: '414', name: 'Steel Gray Dk', hex: '#8c8c8c', active: true },
  { code: '168', name: 'Pewter Very Light', hex: '#d1d1d1', active: true },
  { code: '169', name: 'Pewter Light', hex: '#848484', active: true },
  { code: '317', name: 'Pewter Gray', hex: '#6c6c6c', active: true },
  { code: '413', name: 'Pewter Gray Dark', hex: '#565656', active: true },
  { code: '3799', name: 'Pewter Gray Vy Dk', hex: '#424242', active: true },
  { code: '310', name: 'Black', hex: '#000000', active: true },
];
